version: "3.2"
services:
  redis:
    container_name: redis-cont
    image: redis:alpine
    environment:
      - REDIS_REPLICATION_MODE=master
    ports:
      - 6379:6379
    volumes:
      # 
      - /nfs/redis/redis-data:/data
    command:
      # Save if 100 keys are added in every 10 seconds
      - --save 10 100

  redisinsight: # redis dashboard
    container_name: redisinsight-cont
    image: redislabs/redisinsight
    ports:
      - 8001:8001
    volumes:
      - redisinsight:/db

volumes:
  redis-data:
  redisinsight:
